# Generated by Django 4.2.11 on 2024-03-12 12:39

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doggo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.IntegerField(choices=[(0, 'Unsexed'), (1, 'Female'), (2, 'Male')], default=0)),
                ('breed', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=200)),
                ('age', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Registered'), (2, 'Assesment'), (3, 'Vet-Check'), (4, 'Ready'), (5, 'Fostered'), (6, 'Advised')], default=0)),
                ('vet_checked', models.DateTimeField()),
                ('vet_note', models.TextField()),
                ('vet_medication', models.TextField()),
                ('vet_vaccinated', models.DateTimeField()),
                ('vet_neutered', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('temperament', models.TextField()),
                ('training', models.TextField()),
                ('behaviour', models.TextField()),
                ('notes', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_on'],
            },
        ),
    ]
