# Generated by Django 4.2.11 on 2024-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doggo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Registered'), (2, 'Assesment'), (3, 'Vet-Check'), (4, 'Ready'), (5, 'Fostered'), (6, 'Adopted')], default=0),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_checked',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_vaccinated',
            field=models.DateField(),
        ),
    ]
