# Generated by Django 4.2.11 on 2024-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo', '0002_alter_doggo_status_alter_doggo_vet_checked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doggo',
            options={'ordering': ['-added_on']},
        ),
        migrations.AlterField(
            model_name='doggo',
            name='behaviour',
            field=models.TextField(default='Under Assesment'),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='notes',
            field=models.TextField(default='Under Assesment'),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='temperament',
            field=models.TextField(default='Under Assesment'),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='training',
            field=models.TextField(default='Under Assesment'),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_checked',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_medication',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_vaccinated',
            field=models.DateField(blank=True),
        ),
    ]
