# Generated by Django 4.2.11 on 2024-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo', '0003_alter_doggo_options_alter_doggo_behaviour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doggo',
            name='vet_checked',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_vaccinated',
            field=models.DateField(),
        ),
    ]
