# Generated by Django 4.2.11 on 2024-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo', '0004_alter_doggo_vet_checked_alter_doggo_vet_vaccinated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doggo',
            name='behaviour',
            field=models.TextField(default='Under Assessment'),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='notes',
            field=models.TextField(default='Under Assessment'),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='temperament',
            field=models.TextField(default='Under Assessment'),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='training',
            field=models.TextField(default='Under Assessment'),
        ),
    ]
