# Generated by Django 4.2.11 on 2024-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo', '0005_alter_doggo_behaviour_alter_doggo_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggo',
            name='vet_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Weight (kg)'),
        ),
    ]
