# Generated by Django 4.2.11 on 2024-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo', '0006_doggo_vet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doggo',
            name='vet_checked',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_vaccinated',
            field=models.DateField(blank=True),
        ),
    ]
