# Generated by Django 4.2.11 on 2024-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggo', '0007_alter_doggo_vet_checked_alter_doggo_vet_vaccinated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doggo',
            name='vet_checked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doggo',
            name='vet_vaccinated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
